# Generated by Django 4.2 on 2023-04-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='When Modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('done', 'Done')], default='todo', max_length=10, verbose_name='Status'),
        ),
    ]
